DEFAULT sockit-netan
TIMEOUT 10
LABEL sockit-netan
  KERNEL /zImage
  FDT /socfpga_cyclone5_sockit.dtb
  APPEND console=tty0 console=ttyS0,115200 fbcon=map:0 fbcon=font:MINI4x6 consoleblank=0 root=/dev/mmcblk0p3 rw rootwait
