#!/bin/sh
# install.sh — drop the netan network analyzer onto any Linux host.
#
# Installs the board-agnostic core (net-analyzer, netan-iperf, netan-mode) and,
# unless one already exists, an /etc/netan.conf. Defaults to GUEST model, which
# only OBSERVES the host's existing connection and never touches the interface —
# safe to run on a machine you're using. Pass --model appliance only on a
# dedicated box you want to own the NIC (DHCP release/renew each cycle).
#
# Usage:
#   ./install.sh [options]
#     --prefix DIR     install prefix (default /usr/local => bin in /usr/local/bin)
#     --model M        guest (default) | appliance
#     --iface IFACE    pin the interface (default: auto-detect)
#     --label TEXT     report label (default: netan@<hostname>)
#     --service        install + enable a systemd service (netan.service)
#     --display [VT]    also show the dashboard on a console VT (default 8) via a
#                       netan-display.service (large font, coexists with a desktop)
#     --start          run once in the foreground now (Ctrl-C to stop)
#     --uninstall      remove installed files, the services, and /etc/netan.conf
#   Run as root (writes $prefix/bin, /etc, and systemd units).
set -eu

SRC=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
PREFIX=/usr/local
MODEL=guest
IFACE=
LABEL=
DO_SERVICE=0
DO_START=0
DO_UNINSTALL=0
DO_DISPLAY=0
DISPLAY_VT=8

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)    PREFIX=$2; shift 2 ;;
        --model)     MODEL=$2; shift 2 ;;
        --iface)     IFACE=$2; shift 2 ;;
        --label)     LABEL=$2; shift 2 ;;
        --service)   DO_SERVICE=1; shift ;;
        --display)   DO_DISPLAY=1; case "${2:-}" in [0-9]*) DISPLAY_VT=$2; shift 2 ;; *) shift ;; esac ;;
        --start)     DO_START=1; shift ;;
        --uninstall) DO_UNINSTALL=1; shift ;;
        -h|--help)   sed -n '2,26p' "$0"; exit 0 ;;
        *) echo "install.sh: unknown option: $1" >&2; exit 2 ;;
    esac
done

BINDIR=$PREFIX/bin
UNIT=/etc/systemd/system/netan.service
DUNIT=/etc/systemd/system/netan-display.service

if [ "$DO_UNINSTALL" = 1 ]; then
    if command -v systemctl >/dev/null 2>&1; then
        for svc in netan.service netan-display.service; do
            [ -f "/etc/systemd/system/$svc" ] && systemctl disable --now "$svc" 2>/dev/null || true
        done
        rm -f "$UNIT" "$DUNIT"; systemctl daemon-reload 2>/dev/null || true
    fi
    rm -f "$BINDIR/net-analyzer" "$BINDIR/netan-iperf" "$BINDIR/netan-mode" "$BINDIR/netan-display"
    rm -f /etc/netan.conf /tmp/netan-mode
    echo "netan: uninstalled from $BINDIR (left /var/log/net-analyzer.log if any)"
    exit 0
fi

case "$MODEL" in guest|appliance) ;; *) echo "install.sh: --model must be guest or appliance" >&2; exit 2 ;; esac

echo "netan: installing core -> $BINDIR (model=$MODEL)"
mkdir -p "$BINDIR"
for f in net-analyzer netan-iperf netan-mode netan-display; do
    install -m 0755 "$SRC/bin/$f" "$BINDIR/$f"
done

# dependency check — warn, don't fail (the analyzer degrades gracefully)
miss=
for dep in ip ping nslookup wget arp-scan; do
    command -v "$dep" >/dev/null 2>&1 || miss="$miss $dep"
done
command -v iperf3 >/dev/null 2>&1 || miss="$miss iperf3(iperf-mode)"
[ -n "$miss" ] && echo "netan: WARNING missing tools (reduced function):$miss" >&2

# config — never clobber an existing one
if [ -f /etc/netan.conf ]; then
    echo "netan: keeping existing /etc/netan.conf (edit it by hand to change)"
else
    {
        echo "# generated by netan install.sh"
        echo "NETAN_MODEL=$MODEL"
        [ -n "$IFACE" ] && echo "NETAN_IFACE=$IFACE"
        [ -n "$LABEL" ] && echo "NETAN_LABEL=$LABEL"
    } > /etc/netan.conf
    echo "netan: wrote /etc/netan.conf (see $SRC/netan.conf.sample for all knobs)"
fi

if [ "$DO_SERVICE" = 1 ]; then
    if command -v systemctl >/dev/null 2>&1; then
        cat > "$UNIT" <<EOF
[Unit]
Description=netan network analyzer ($MODEL)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=$BINDIR/net-analyzer
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
        systemctl daemon-reload
        systemctl enable --now netan.service
        echo "netan: systemd service enabled + started (journalctl -u netan -f)"
    else
        echo "netan: no systemd here — start it yourself, e.g.:"
        echo "         $BINDIR/net-analyzer >>/var/log/net-analyzer.log 2>&1 &"
    fi
fi

if [ "$DO_DISPLAY" = 1 ]; then
    if command -v systemctl >/dev/null 2>&1; then
        SETFONT=$(command -v setfont 2>/dev/null || true)
        CHVT=$(command -v chvt 2>/dev/null || true)
        # a large console font (32px tall) so the 80x24 dashboard fills a monitor;
        # fall back silently to the default font if none is installed
        FONT=$(ls /usr/share/consolefonts/ 2>/dev/null | grep -iE 'Terminus32x16' | head -1)
        FONT=${FONT%.psf.gz}; FONT=${FONT%.psfu.gz}; FONT=${FONT%.psf}
        {
            echo "[Unit]"
            echo "Description=netan console status dashboard (vt$DISPLAY_VT)"
            echo "After=netan.service display-manager.service"
            echo "Wants=netan.service"
            echo ""
            echo "[Service]"
            echo "Type=simple"
            [ -n "$SETFONT" ] && [ -n "$FONT" ] && \
                echo "ExecStartPre=-$SETFONT -C /dev/tty$DISPLAY_VT $FONT"
            [ -n "$CHVT" ] && echo "ExecStartPre=-$CHVT $DISPLAY_VT"
            echo "ExecStart=$BINDIR/netan-display --tty /dev/tty$DISPLAY_VT --refresh 3"
            echo "Restart=always"
            echo "RestartSec=3"
            echo ""
            echo "[Install]"
            echo "WantedBy=multi-user.target"
        } > "$DUNIT"
        systemctl daemon-reload
        systemctl enable --now netan-display.service
        echo "netan: dashboard on VT$DISPLAY_VT (font ${FONT:-default}) — coexists with a"
        echo "       desktop; 'chvt <n>' switches the monitor. journalctl -u netan-display -f"
    else
        echo "netan: --display needs systemd; else run: netan-display --tty /dev/ttyN &" >&2
    fi
fi

if [ "$DO_START" = 1 ]; then
    echo "netan: running in the foreground (Ctrl-C to stop) ..."
    exec "$BINDIR/net-analyzer"
fi

[ "$DO_SERVICE" = 0 ] && [ "$DO_START" = 0 ] && \
    echo "netan: installed. Run '$BINDIR/net-analyzer' or re-run with --service / --start."
exit 0
